export enum UserRole {
  CLEANER = "MYJKOWY",
  MECHANIC = "TECHNICZNY",
  COORDINATOR = "KOORDYNATOR",
  CLIENT = "KLIENT",
}

export enum LoginUserRole {
  CLEANER = "PRACOWNIK MYJNI",
  MECHANIC = "MECHANIK",
  COORDINATOR = "KOORDYNATOR",
  CLIENT = "KLIENT",
}

export type UserRoleKey = "CLEANER" | "MECHANIC" | "COORDINATOR" | "CLIENT";
