export enum CardType {
  DEFAULT = "DEFAULT",
  PHOTO_LAST = "PHOTO_LAST",
  PHOTO_SINGLE_COLUMN = "PHOTO_SINGLE_COLUMN",
  WITH_BUTTON = "WITH_BUTTON",
  CAR_CARD = "CAR_CARD",
  CUSTOM = "CUSTOM",
}
